config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'magic_items#index'
  resources :magic_items
  get '/search', to: "magic_items#search"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/magic_item.rb
class MagicItem < ApplicationRecord
  validates :name, presence: true
  validates :item_type, presence: true
  validates :rarity, presence: true
  validates :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/magic_items_controller.rb
class MagicItemsController < ApplicationController
  before_action :set_magic_item, only:[:show, :update, :edit, :destroy]

  def index
    # @magic_items = render({json: MagicItem.all})
    @magic_items = MagicItem.all
  end

  def new
    @magic_item = MagicItem.new
  end

  def create
    @magic_item = MagicItem.new(magic_item_params)
    @magic_item.save
    redirect_to magic_item_path(@magic_item)
  end

  def show
  end

  def edit
  end

  def update
    @magic_item.update(magic_item_params)
    redirect_to magic_item_path(@magic_item)
  end

  def destroy
    @magic_item.destroy
    redirect_to magic_items_path
  end

  def search
    if params[:search].blank?
      redirect_to magic_items_path
    else
      @parameter = params[:search].downcase
      @results = index.where("lower(name) LIKE :search", search: "%#{@parameter}%")
    end
  end

  private

  def magic_item_params
    params.require(:magic_item).permit(:name, :item_type, :description, :rarity, :attunement)
  end

  def set_magic_item
    @magic_item = MagicItem.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/magic_items_helper.rb
module MagicItemsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsDndMagicItems</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Luxurious+Roman&display=swap" rel="stylesheet">
  </head>

  <body>
    <nav class="navbar sticky-top navbar-expand-lg navbar-dark bg-dark">
      <%= link_to "Merls Magic Items", magic_items_path, class: "navbar-brand" %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <%= link_to "Add Homebrew", new_magic_item_path, class: "nav-item nav-link" %>
        </div>
       <%= form_tag(search_path, :method => "get") do %>
       <div class="input-group">
         <%= search_field_tag :search, params[:search], placeholder: 'Search for item name', class: "form-control" %>
         <div class="input-group-btn">
           <%= button_tag "Search", :class => "btn btn-info glyphicon glyphicon-search", :name => nil%>
         </div>
       </div>
       <% end %>
      </div>
    </nav>
    <%= yield %>
    <div class="footer">
      <div class= "container">
        <footer>
            <p>Author: Laura Brooks</p>
            <p>Built using the Open5e API</p>
        </footer>
      </div>
    </div>
  </body>
</html>

app/views/magic_items/edit.html.erb
<div class="container my-4">
    <%= simple_form_for(@magic_item) do |f| %>
      <%= f.input :name, :placeholder => "Item name: Bag of Holding, Wand of Conjuring, etc" %>
      <%= f.input :item_type, :placeholder => "Item Type: Armor, Wand, Bag, etc" %>
      <%= f.input :rarity, :placeholder => "Rarity: rare, uncommon, etc" %>
      <%= f.input :description, :placeholder => "Item description", :as => :text %>
      <%= f.input :attunement, :placeholder => "Requires attunement" %>
      <%= f.submit class: "button"%>
      <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
    <% end %>
  <%= link_to "Back", magic_items_path %>
</div>

app/views/magic_items/index.html.erb
<div class="container my-4 py-2">
  <% @magic_items.each do |item| %>
    <div class="card">
      <h2><%= item.name %></h2>
      <h3> <%= item.item_type %></h3>
      <h6> <%= item.rarity.capitalize %></h6>
      <p> <%= item.description.truncate(300) %> <p>
      <h6><%= item.attunement.capitalize %></h6>
      <br>
      <%= link_to "More..", magic_item_path(item), class: "button" %>
    </div>
  <% end %>

</div>

app/views/magic_items/new.html.erb
<div class="container my-4">
    <%= simple_form_for(@magic_item) do |f| %>
      <%= f.input :name, :placeholder => "Item name: Bag of Holding, Wand of Conjuring, etc" %>
      <%= f.input :item_type, :placeholder => "Item Type: Armor, Wand, Bag, etc" %>
      <%= f.input :rarity, :placeholder => "Rarity: rare, uncommon, etc" %>
      <%= f.input :description, :placeholder => "Item description", :as => :text %>
      <%= f.input :attunement, :placeholder => "Requires attunement" %>
      <%= f.submit class: "button"%>
      <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
    <% end %>
  <%= link_to "Back", magic_items_path %>
</div>

app/views/magic_items/search.html.erb
<div class="container">
 <h2 class= "pl-4 py-3">Search Results</h2>
  <% @results.map do |result| %>
   <div class="card">
    <h2><%= result.name %></h2>
    <h3><%= result.item_type %></h3>
    <h6><%= result.rarity.capitalize %></h6>
    <p><%= result.description.truncate(300) %></p>
    <h6><%= result.attunement.capitalize %></h6>
    <br>
    <%= link_to "More..", magic_item_path(result), class: "button" %>
   </div>
  <% end %>

</div>

app/views/magic_items/show.html.erb
<div class="container my-4 mb-5 pb-5">
  <div class="show-card">
    <h2><%= @magic_item.name %>
    <%= link_to magic_item_path(@magic_item), class: 'link-icon', method: :delete, data: { confirm: "Are you sure?"} do %>
      <i class="fa fa-trash"></i>
    <% end %>
    <%= link_to edit_magic_item_path(@magic_item), class: 'link-icon' do %>
      <i class="fas fa-pencil-alt"></i>
    <% end %></h2>
    <h3><%= @magic_item.item_type %></h3>
    <h6><%= @magic_item.rarity.capitalize %></h6>
    <p><%= @magic_item.description %></p>
    <h6><%= @magic_item.attunement.capitalize %></h6>
  </div>
  <%= link_to "Back", magic_items_path, class: 'link' %>
</div>